name: jp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/assets1/hintergruende/
    - assets/assets1/hintergruende/bg_startscreen.png
    - assets/assets1/grafiken/
    - assets/assets1/hintergruende/
    - assets/assets1/details/
    - assets/assets2/grafiken/
    - assets/assets2/details/
